spring.application.name=swiggy-backend-clone

spring.mongodb.uri=mongodb://vangapranathi_db_user:byqrUwVz4iyf2oDi@ac-vmirqcq-shard-00-00.xfovbnu.mongodb.net:27017,ac-vmirqcq-shard-00-01.xfovbnu.mongodb.net:27017,ac-vmirqcq-shard-00-02.xfovbnu.mongodb.net:27017/?ssl=true&replicaSet=atlas-cjkcof-shard-0&authSource=admin&appName=swiggy-cluster

spring.mongodb.database=swiggy_backend

server.port=9090
#byqrUwVz4iyf2oDi
#vangapranathi_db_user